# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            A Man's Musings
tagline:          'A collection of reflections.'
description:      'A personal collection of notes, thoughts, and reflections made by <a href="https://www.instagram.com/jakelundkovsky/" target="_blank">@jakelundkovsky</a>.'
url:              http://hyde.getpoole.com
baseurl:          http://jakelundkovsky.github.io/aMansMusings/

author:
  name:           'Jake Lundkovsky'
  url:            https://www.instagram.com/jakelundkovsky/

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jakelundkovsky/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown
